import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { PNG } from 'pngjs';

import { wallSideSource } from '../scene-builder';

/**
 * The pixel proof that a wall box cannot be see-through.
 *
 * Every other test in this area asserts a RECTANGLE — that the builder hands over the `-f` cell,
 * cropped. None of them can tell whether that rectangle is actually opaque, which is exactly how
 * the original bug shipped: the code swapped `tile.wall-villa-5` (81% opaque) for
 * `tile.wall-villa-f` and called it solid. `-f` is 95.9% opaque. The remaining 42 texels are the
 * rounded corners of the top-down stamp, and `atlasCell` maps the sprite's bottom row to the BOTTOM
 * of a vertical face, so they rendered as a notch on the wall/ground line once per tile.
 *
 * So this test reads the atlas and checks alpha. It fails if the art is ever redrawn with a wider
 * margin than `WALL_SIDE_INSET_TEXELS` crops, which a rectangle assertion would sail straight past.
 *
 * Reading the committed PNG in a unit test has precedent: `src/render/__tests__/mask-frame.test.ts`
 * does the same, and for the same reason — the check must run without a build.
 */
const atlas = PNG.sync.read(readFileSync(resolve('assets/generated/world-atlas.png')));

/** The same cutoff the renderer uses. See `alphaTest: 0.5` in `world-renderer-25.ts`. */
const ALPHA_TEST_CUTOFF = 128;

/**
 * One sprite per wall family, plus a family's own `-f`.
 *
 * `indoorFrame()` is the villa map only, so a builder-driven test would never look at civic,
 * commercial or downtown. Their art is generated by the same builder, so a margin change would hit
 * all four at once and a villa-only test would still pass on three broken families.
 *
 * `tile.wall-villa-f` is here because it is the mask-15 case that used to get `sideSource:
 * undefined` and fall back to the uncropped cell.
 */
const SPRITES = [
  'tile.wall-civic-0',
  'tile.wall-commercial-0',
  'tile.wall-downtown-0',
  'tile.wall-villa-0',
  'tile.wall-villa-f',
] as const;

describe('wall side textures are opaque where it counts', () => {
  test.each(SPRITES)('%s yields a fully opaque side cell', (sprite) => {
    const side = wallSideSource(sprite);
    expect(side).toBeDefined();
    expect({ width: side!.width, height: side!.height }).toEqual({ width: 24, height: 32 });

    const cut: string[] = [];
    for (let row = 0; row < side!.height; row += 1) {
      for (let column = 0; column < side!.width; column += 1) {
        const index = ((side!.y + row) * atlas.width + side!.x + column) * 4 + 3;
        if (atlas.data[index]! < ALPHA_TEST_CUTOFF) cut.push(`${column},${row}`);
      }
    }
    // Listing the offenders rather than a bare count: a failure here means the art moved, and the
    // coordinates say which margin grew.
    expect({ sprite, cut }).toEqual({ sprite, cut: [] });
  });

  /**
   * The crop has to be a real crop. If `WALL_SIDE_INSET_TEXELS` were ever set to 0 the rectangle
   * assertions above would still pass on width, so pin that the uncropped cell is genuinely holed.
   * This is the measurement the whole fix rests on.
   */
  test('the uncropped -f cell is NOT opaque, which is why the crop exists', () => {
    const side = wallSideSource('tile.wall-villa-0')!;
    let cut = 0;
    for (let row = 0; row < 32; row += 1) {
      for (let column = -4; column < 28; column += 1) {
        const index = ((side.y + row) * atlas.width + side.x + column) * 4 + 3;
        if (atlas.data[index]! < ALPHA_TEST_CUTOFF) cut += 1;
      }
    }
    expect(cut).toBe(42);
  });
});
