import { z } from 'zod';

import { CommandIdSchema, EventIdSchema, PauseTokenSchema, StableIdSchema } from '../state/ids';
import { SimulationSpeedSchema } from '../clock/clock';
import { PoliceHookSchema } from '../consequences/police';
import { VERBAL_MISSION_OUTCOMES } from '../verbal-missions/contracts';

const EventBaseSchema = z.object({
  eventId: EventIdSchema,
  commandId: CommandIdSchema,
  sequence: z.number().int().nonnegative(),
  absoluteMinute: z.number().int().nonnegative(),
}).strict();

export const DomainEventSchema = z.discriminatedUnion('type', [
  EventBaseSchema.extend({
    type: z.literal('clock-advanced'),
    fromMinute: z.number().int().nonnegative(),
    toMinute: z.number().int().nonnegative(),
    consumedRealMilliseconds: z.number().int().nonnegative(),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('pause-token-added'),
    token: PauseTokenSchema,
    changed: z.boolean(),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('pause-token-removed'),
    token: PauseTokenSchema,
    changed: z.boolean(),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('relationship-changed'),
    npcId: StableIdSchema,
    familiarityDelta: z.number().int(),
    trustDelta: z.number().int(),
    attractionDelta: z.number().int(),
    reason: z.string().min(1).max(160),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('faction-standing-changed'),
    factionId: StableIdSchema,
    delta: z.number().int(),
    reason: z.string().min(1).max(160),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('relationship-stage-requested'),
    npcId: StableIdSchema,
    fromStage: z.enum(['stranger', 'acquaintance', 'friend', 'dating', 'partner', 'engaged', 'married']),
    targetStage: z.enum(['acquaintance', 'friend', 'dating', 'partner', 'engaged', 'married']),
    accepted: z.boolean(),
    reasonId: StableIdSchema,
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('home-invitation-responded'),
    invitationId: StableIdSchema,
    npcId: StableIdSchema,
    outcome: z.enum(['accepted', 'rejected', 'countered', 'replan_required', 'completed', 'cancelled']),
    reasonId: StableIdSchema,
    changed: z.boolean(),
    transferId: StableIdSchema.optional(),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('home-invitation-cancelled'),
    invitationId: StableIdSchema,
    reasonId: StableIdSchema,
    changed: z.boolean(),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('faction-revealed'),
    factionId: StableIdSchema,
    discoveryFlagId: StableIdSchema,
    sourceType: z.enum(['scene_observation', 'authored_event']),
    sourceId: StableIdSchema,
    changed: z.boolean(),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('journal-entry-upserted'),
    entryId: StableIdSchema,
    questId: StableIdSchema,
    locationPrecision: z.enum(['none', 'vague', 'exact']),
    markerVisible: z.boolean(),
    changed: z.boolean(),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('social-option-purchased'),
    offerId: StableIdSchema,
    questId: StableIdSchema,
    grantedQuestFlagId: StableIdSchema,
    amount: z.number().int().nonnegative(),
    changed: z.boolean(),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('linda-quest-started'),
    questId: StableIdSchema,
    requestNpcId: StableIdSchema,
    journalEntryId: StableIdSchema,
    reason: z.string().trim().min(1).max(240),
    grantedItemId: StableIdSchema,
    grantedItemCount: z.number().int().nonnegative(),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('linda-villa-discovered'),
    questId: StableIdSchema,
    journalEntryId: StableIdSchema,
    changed: z.boolean(),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('linda-quest-resolved'),
    questId: StableIdSchema,
    approachId: z.enum(['protect_linda', 'betray_linda', 'withdraw']),
    resultId: StableIdSchema,
    terminalStatus: z.enum(['resolved', 'failed', 'withdrawn']),
    reason: z.string().trim().min(1).max(240),
    familiarityDelta: z.number().int(),
    trustDelta: z.number().int(),
    attractionDelta: z.number().int(),
    factionId: StableIdSchema.optional(),
    factionDelta: z.number().int(),
    rewardAmount: z.number().int().nonnegative(),
    healthDelta: z.number().int(),
    timeDeltaMinutes: z.number().int().nonnegative(),
    evidenceId: StableIdSchema.optional(),
    witnessNpcIds: z.array(StableIdSchema),
    policeFrom: z.enum(['none', 'noticed', 'questioned', 'wanted', 'arrest-on-sight']),
    policeTo: z.enum(['none', 'noticed', 'questioned', 'wanted', 'arrest-on-sight']),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('police-attention-advanced'),
    evidenceId: StableIdSchema,
    hook: PoliceHookSchema,
    from: z.enum(['noticed', 'questioned', 'wanted']),
    to: z.enum(['questioned', 'wanted', 'arrest-on-sight']),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('protagonist-moved'),
    mapId: StableIdSchema,
    locationId: StableIdSchema,
    fromTileX: z.number().int().min(0).max(63),
    fromTileY: z.number().int().min(0).max(47),
    toTileX: z.number().int().min(0).max(63),
    toTileY: z.number().int().min(0).max(47),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('simulation-speed-changed'),
    fromSpeed: SimulationSpeedSchema,
    toSpeed: SimulationSpeedSchema,
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('simulation-advanced'),
    fromMinute: z.number().int().nonnegative(),
    toMinute: z.number().int().nonnegative(),
    consumedRealMilliseconds: z.number().int().nonnegative(),
    milestoneIds: z.array(z.string().min(1).max(160)),
    energyDelta: z.number().int(),
    moneyDelta: z.number().int(),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('sleep-completed'),
    mode: z.enum(['nap', 'overnight']),
    fromMinute: z.number().int().nonnegative(),
    toMinute: z.number().int().nonnegative(),
    energyDelta: z.number().int(),
    milestoneIds: z.array(z.string().min(1).max(160)),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('dev-time-jumped'),
    fromMinute: z.number().int().nonnegative(),
    toMinute: z.number().int().nonnegative(),
    milestoneIds: z.array(z.string().min(1).max(160)),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('quest-reward-applied'),
    rewardKind: z.enum(['ordinary', 'dangerous']),
    amount: z.number().int().nonnegative(),
    questId: StableIdSchema,
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('npc-moved'),
    npcId: StableIdSchema,
    mapId: StableIdSchema,
    fromTileX: z.number().int().min(0).max(63),
    fromTileY: z.number().int().min(0).max(47),
    toTileX: z.number().int().min(0).max(63),
    toTileY: z.number().int().min(0).max(47),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('npc-goal-completed'),
    npcId: StableIdSchema,
    activityId: StableIdSchema,
    locationId: StableIdSchema,
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('npc-transfer-departed'),
    npcId: StableIdSchema,
    transferId: StableIdSchema,
    originMapId: StableIdSchema,
    destinationMapId: StableIdSchema,
    arrivalMinute: z.number().int().nonnegative(),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('protagonist-transitioned'),
    originMapId: StableIdSchema,
    destinationMapId: StableIdSchema,
    sourcePortalId: StableIdSchema,
    destinationEntranceId: StableIdSchema,
    tileX: z.number().int().min(0).max(63),
    tileY: z.number().int().min(0).max(47),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('conversation-committed'),
    conversationId: StableIdSchema,
    npcId: StableIdSchema,
    knowledgeCount: z.number().int().nonnegative(),
    interestCount: z.number().int().nonnegative(),
    unlockCount: z.number().int().nonnegative(),
    memoryCount: z.number().int().nonnegative(),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('verbal-mission-offered'),
    missionId: StableIdSchema,
    npcId: StableIdSchema,
    journalEntryId: StableIdSchema,
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('verbal-mission-outcome-applied'),
    missionId: StableIdSchema,
    outcomeId: StableIdSchema,
    outcome: z.enum(VERBAL_MISSION_OUTCOMES),
    reactionId: StableIdSchema,
    fromStatus: z.enum(['available', 'active']),
    toStatus: z.literal('active'),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('verbal-mission-withdrawn'),
    missionId: StableIdSchema,
    resultId: StableIdSchema,
    journalReceiptId: StableIdSchema,
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('player-knowledge-recorded'),
    factId: StableIdSchema,
    sourceId: StableIdSchema,
    changed: z.boolean(),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('fact-disclosure-recorded'),
    missionId: StableIdSchema,
    factId: StableIdSchema,
    resultId: StableIdSchema,
    journalReceiptId: StableIdSchema,
    familiarityDelta: z.number().int(),
    trustDelta: z.number().int(),
    attractionDelta: z.number().int(),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('unique-object-purchased'),
    missionId: StableIdSchema,
    objectId: StableIdSchema,
    amount: z.number().int().nonnegative(),
    resultId: StableIdSchema,
    journalReceiptId: StableIdSchema,
    familiarityDelta: z.number().int(),
    trustDelta: z.number().int(),
    attractionDelta: z.number().int(),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('scheduled-commitment-created'),
    missionId: StableIdSchema,
    commitmentId: StableIdSchema,
    scheduledMinute: z.number().int().nonnegative(),
    journalReceiptId: StableIdSchema,
    familiarityDelta: z.number().int(),
    trustDelta: z.number().int(),
    attractionDelta: z.number().int(),
  }).strict(),
  EventBaseSchema.extend({
    type: z.literal('scheduled-commitment-resolved'),
    missionId: StableIdSchema,
    commitmentId: StableIdSchema,
    result: z.enum(['honoured', 'delayed', 'reneged']),
    reasonId: StableIdSchema.optional(),
    scheduledMinute: z.number().int().nonnegative().optional(),
    journalReceiptId: StableIdSchema,
    familiarityDelta: z.number().int(),
    trustDelta: z.number().int(),
    attractionDelta: z.number().int(),
  }).strict(),
]);

export type DomainEvent = z.infer<typeof DomainEventSchema>;
